# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  inputs:
    filePath: './scripts/build_pipeline.sh'
    arguments: '$(System.DefaultWorkingDirectory) $(Build.ArtifactStagingDirectory) $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- upload: $(Build.ArtifactStagingDirectory)
  displayName: 'Publish package'
  artifact: drop